# Generated by Django 2.1.4 on 2019-02-07 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20190109_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliment',
            old_name='carbohydrates_100g',
            new_name='saturated_fat_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='carbohydrates_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='energy_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='energy_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='fat_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='fat_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='fiber_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='fiber_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='id_categorie',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='proteins_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='proteins_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='salt_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='salt_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='saturatedfat_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='saturatedfat_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='sodium_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='sodium_unit',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='sugars_100g',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='sugars_unit',
        ),
        migrations.AddField(
            model_name='aliment',
            name='categorie',
            field=models.CharField(default='erreur', max_length=100),
        ),
        migrations.AddField(
            model_name='aliment',
            name='code',
            field=models.CharField(default='erreur', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='product_name',
            field=models.CharField(default='erreur', max_length=200),
        ),
        migrations.AddField(
            model_name='aliment',
            name='url_thumb_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='nutrition_score',
            field=models.CharField(default='erreur', max_length=10),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='categorie_name',
            field=models.CharField(default='rien', max_length=100),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
